#!/usr/bin/env python3
"""Generate the Ada golden-oracle package from the HTTP client corpus."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from http_client_corpus import load, validate


def ada_name(value: str) -> str:
    return "_".join(
        part[:1].upper() + part[1:]
        for part in re.split(r"[^A-Za-z0-9]+", value)
        if part
    )


def boolean(value: bool) -> str:
    return "True" if value else "False"


def enum_set(values: list[str], names: dict[str, str]) -> str:
    if set(values) == set(names):
        return "(others => True)"
    entries = ", ".join(f"{names[value]} => True" for value in values)
    return f"({entries}, others => False)"


def optional_boolean(value: bool | None) -> str:
    if value is None:
        return "Ignored"
    return "Required_True" if value else "Required_False"


def render_spec(document: dict) -> str:
    cases = document["cases"]
    case_names = {case["id"]: ada_name(case["id"]) for case in cases}
    protocol_names = {value: value.upper() for value in ("h1", "h2", "h3")}
    api_names = {
        value: ada_name(value)
        for value in ("sync-head", "scoped-buffer", "scoped-sink", "established-child")
    }
    result_values = sorted({
        "response-complete",
        "pre-admission-rejected",
        "cancelled",
        "timed-out",
        "client-unavailable",
        "connection-failed",
        "transport-failed",
        "request-source-failed",
        "response-invalid",
        "response-body-too-large",
        "response-sink-failed",
    } | {case["expect"]["kind"] for case in cases} | {
        case["expect"]["sibling_kind"]
        for case in cases
        if "sibling_kind" in case["expect"]
    })
    certainty_values = sorted({case["expect"]["certainty"] for case in cases})
    body_values = sorted({case["expect"]["body_effect"] for case in cases})
    result_names = {value: ada_name(value) for value in result_values}
    certainty_names = {value: ada_name(value) for value in certainty_values}
    body_names = {value: ada_name(value) for value in body_values}

    lines = [
        "--  Generated by tests/generate_http_client_corpus.py; do not edit.",
        "package HTTP_Client_Corpus_Golden is",
        "   type Case_Kind is",
        "     (" + ",\n      ".join(case_names.values()) + ");",
        "   type Protocol_Kind is (H1, H2, H3);",
        "   type API_Style is",
        "     (" + ", ".join(api_names.values()) + ");",
        "   type Result_Kind is",
        "     (" + ",\n      ".join(result_names.values()) + ");",
        "   type Certainty_Kind is",
        "     (" + ",\n      ".join(certainty_names.values()) + ");",
        "   type Body_Effect_Kind is",
        "     (" + ",\n      ".join(body_names.values()) + ");",
        "   type Boolean_Expectation is (Ignored, Required_False, Required_True);",
        "   type Protocol_Set is array (Protocol_Kind) of Boolean;",
        "   type API_Set is array (API_Style) of Boolean;",
        "",
        "   type Expected_Observation is record",
        "      Kind                  : Result_Kind;",
        "      Certainty             : Certainty_Kind;",
        "      Status_Known          : Boolean;",
        "      Status                : Natural;",
        "      Body_Effect           : Body_Effect_Kind;",
        "      Required_Length_Known : Boolean;",
        "      Required_Length       : Natural;",
        "      Source_Releases_Known : Boolean;",
        "      Source_Releases       : Natural;",
        "      Request_Reset         : Boolean_Expectation;",
        "      Automatic_Replay      : Boolean_Expectation;",
        "      Sibling_Kind_Known    : Boolean;",
        "      Sibling_Kind          : Result_Kind;",
        "   end record;",
        "",
        "   type Case_Descriptor is record",
        "      Protocols : Protocol_Set;",
        "      APIs      : API_Set;",
        "      Expected  : Expected_Observation;",
        "   end record;",
        "   type Corpus_Array is array (Case_Kind) of Case_Descriptor;",
        "",
        "   Corpus : constant Corpus_Array :=",
        "     (",
    ]

    rendered_cases: list[str] = []
    for case in cases:
        expected = case["expect"]
        required = expected.get("required_length", {"known": False, "bytes": 0})
        sibling = expected.get("sibling_kind")
        status = expected.get("status")
        source_releases = expected.get("source_releases")
        rendered_cases.append(
            f"{case_names[case['id']]} =>\n"
            f"        (Protocols => {enum_set(case['protocols'], protocol_names)},\n"
            f"         APIs => {enum_set(case['api_styles'], api_names)},\n"
            "         Expected =>\n"
            f"           (Kind => {result_names[expected['kind']]},\n"
            f"            Certainty => {certainty_names[expected['certainty']]},\n"
            f"            Status_Known => {boolean(status is not None)},\n"
            f"            Status => {status or 0},\n"
            f"            Body_Effect => {body_names[expected['body_effect']]},\n"
            f"            Required_Length_Known => {boolean(required['known'])},\n"
            f"            Required_Length => {required['bytes']},\n"
            f"            Source_Releases_Known => {boolean(source_releases is not None)},\n"
            f"            Source_Releases => {source_releases or 0},\n"
            f"            Request_Reset => {optional_boolean(expected.get('request_reset_committed'))},\n"
            f"            Automatic_Replay => {optional_boolean(expected.get('automatic_replay'))},\n"
            f"            Sibling_Kind_Known => {boolean(sibling is not None)},\n"
            f"            Sibling_Kind => {result_names[sibling] if sibling else result_names[result_values[0]]}))"
        )
    lines.append(",\n      ".join(rendered_cases))
    lines.extend(["     );", "end HTTP_Client_Corpus_Golden;", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("corpus", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", type=Path)
    arguments = parser.parse_args()
    if (arguments.output is None) == (arguments.check is None):
        parser.error("exactly one of --output or --check is required")
    document = load(arguments.corpus)
    validate(document, arguments.corpus)
    rendered = render_spec(document)
    if arguments.check is not None:
        checked_in = arguments.check.read_text(encoding="utf-8")
        normalize = lambda value: re.sub(r"\s+", "", value)
        assert normalize(checked_in) == normalize(rendered), (
            f"{arguments.check} is stale; regenerate it from {arguments.corpus}"
        )
    else:
        arguments.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
