name = "flyology_iri_benchmarks"
description = "Corpus benchmarks for flyology_iri"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
licenses = "MIT OR Apache-2.0"
executables = ["flyology_iri_benchmark"]

[[depends-on]]
flyology_iri = "*"

[[pins]]
flyology_iri = { path = ".." }
